# Generated by Django 3.1.5 on 2021-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_username', models.CharField(default='saranya', max_length=50)),
                ('model_password', models.CharField(default='******', max_length=50)),
            ],
        ),
    ]
